version: '3'

services:
  redis:
    build: ./redis
    ports:
      - "6379:6379"

  timeseries:
    build: ./timeseries
    depends_on:
      - "redis"
    links:
      - "redis:redis"
    environment:
      - "REDIS_HOST=${REDIS_HOST:-redis}"
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    build: ./frontend
    depends_on:
      - "timeseries"
    links:
      - "timeseries:timeseries"
    ports:
      - 8000:80
